set -g mouse on
set-option -g renumber-windows on

# Allow xterm titles in terminal window, terminal scrolling with scrollbar, and setting overrides of c-Up, c-Down, c-Left, c-Right
# (commented out because it disables cursor navigation in vim)
#set -g terminal-overrides "xterm*:smcup@:rmcup@:kUP5=\eOA:kDN5=\eOB:kLFT5=\eOC:kRIT5=\eOD"

# set -g default-terminal xterm-256color
set -g default-terminal screen-256color
set-window-option -g xterm-keys on
set -wg mode-keys vi
set -g status-keys vi

# Scroll History
set -g history-limit 30000

# Set ability to capture on start and restore on exit window data when running an application
setw -g alternate-screen on

# Lower escape timing from 500ms to 50ms for quicker response to scroll-buffer access.
set -s escape-time 50

#set -g status-interval 10
#set -g status-right '#(/date.sh 'America/New_York' 'New York') #(/date.sh 'Europe/Paris' 'Paris') #(/date.sh 'Asia/Kolkata' 'India') #(/date.sh 'Asia/Hong_K...
#set -g status-right-length 160

#bind-key -t emacs-copy -n S-PPage halfpage-up
#bind-key -t emacs-copy -n S-NPage halfpage-down
#bind-key -t vi-copy -n S-PPage halfpage-up
#bind-key -t vi-copy -n S-NPage halfpage-down

#bind-key -t root -n S-PPage copy-mode -u

#bind -n Pageup copy-mode -u
#bind -n S-Pageup copy-mode -u
#bind -n S-Pagedown send-keys Pagedown

# Shift-pageup to enter copy mode
bind -n S-Pageup copy-mode -u

#bind -n End send-key C-e
#bind -n Home send-key C-a
bind-key -t copy-mode-vi 'Home' send -X start-of-line
bind-key -t copy-mode-vi 'End' send -X end-of-line

bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Set pane 0 (up pane) height to 30
bind-key ~ resize-pane -t 0 -y 30

bind-key v split-window -h
bind-key s split-window -v

bind -n C-M-Left select-pane -L
bind -n C-M-Right select-pane -R
bind -n C-M-Up select-pane -U
bind -n C-M-Down select-pane -D

# bind -n C-M-S-Right swap-pane -s {right-of}
# bind -n C-M-S-Left swap-pane -s {left-of}
# bind -n C-M-S-Up swap-pane -s {up-of}
# bind -n C-M-S-Down swap-pane -s {down-of}
bind -n C-M-S-Right select-pane -R \; swap-pane -s '!' \; select-pane -R
bind -n C-M-S-Left select-pane -L \; swap-pane -s '!' \; select-pane -L
bind -n C-M-S-Up select-pane -U \; swap-pane -s '!' \; select-pane -U
bind -n C-M-S-Down select-pane -D \; swap-pane -s '!' \; select-pane -D

set -g status-left "#[bg=cyan]#[fg=colour0]#{?client_prefix,#[bg=yellow],} ~]~P #S #{?client_prefix,#[fg=colour2],}#{?window_zoomed_flag, ~V| ,}#[fg=colour1]"
set -g status-right "#[bg=cyan] \"#{=21:pane_title}\" %H:%M %d-%b-%y"
#set -g status-style fg=black,bg=blue
set -g status-style fg=black,bg=colour31
set -g status-justify centre

# set-window-option -g window-status-current-bg yellow
set-window-option -g window-status-current-style 'bg=yellow'
set -g window-status-current-format ' #I:#W[#P] '

#set -g window-active-style 'bg=black'
set -g pane-border-status bottom
#set -g pane-active-border-bg black
#set -g pane-active-border-fg yellow
#set -g pane-active-border-style 'bg=black'
set -g pane-border-style 'fg=yellow,bg=black'
set -g pane-active-border-style 'bg=colour178,fg=black'

bind _ resize-pane -U 100 \; resize-pane -D 100
bind -n C-S-Up resize-pane -U 5
bind -n C-S-Down resize-pane -D 5
bind -n C-S-Left resize-pane -L 5
bind -n C-S-Right resize-pane -R 5
